fga-eps-mds/2019.2-Vsign

docs/architectureDocument/doc.md
mkdocs.yml

Added the Architecture Document (doc.md) inside /docs and added the topic inside nav.

Architecture document

---

docs/managementProject/vision-document.md

Criando arquivo no formato markdown para a pagina do documento de visão e adicionando a Introdução(parcial), o Posicionamento(parcial) e a estrutura geral do documento.

Create Vision Document markdown archive for documentation

---

docs/project/vision-document.md

Sentença de posicionamento, complemento da descrição do problema, visão geral do documento, referências, envolvidos, revisão do documento, adicionados ao documento de visão.

Contribuição ao documento de visão

---

.circleci/config.yml

Explicar as mudanças feitas nesse pull request, referenciando as issues que foram resolvidas com esse pull request e os responsáveis por ela.<br>
Ex: Foi feito o documento A (#12 - @caue96 e @thiagorpereira) para que possamos visualizar melhor o contexto do projeto e modificado o documento B (#28 - @victoralvesgomide) para atualizar proposta de projeto;<br>
**Checklist**

Insert config.yml of Circle CI

---

backend/config/routes.rb

Foi colocado `v1` no arquivo de rotas para a API Rest (#54 @MarcosFloresta) <br>
**Checklist**

US05 - Versionar API Rest

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/components/read.txt

Foi feita a instalação do pacote react-router-dom para o roteamento das views e um estruturação das pastas para uma melhor organização;<br>
**Checklist**

Criar a estrutura de pastas para o frontend

---

docs/managementProject/styleGuide.md
mkdocs.yml

Documento que busca fornecer um padrão para a implementação do código;

Inserção do Doc: Folha de Estilo

---

frontend/package-lock.json
frontend/package.json

Apenas foi instalada a biblioteca RSuite para usarmos na refatoração do design.
**Checklist**

Install design library

---

backend/Gemfile.lock
backend/app/controllers/v1/contracts_controller.rb
backend/app/models/script.rb

Foi implementada a funcionalidade de criar novos contratos para as empresas, com base nos dados recebidos por um endpoint. (#53 @MarcosFloresta) <br>
**Checklist**

US04 - Criar novos contratos 

---

backend/Gemfile.lock

Implementação da funcionalidade de notificar o usuário com o _status_ da sua assinatura, usando o 
[SendGrid](https://sendgrid.com/) . (#59 @MarcosFloresta) <br>
**Checklist**

US10 - Notificar usuário sobre resultado da assinatura

---

frontend/Dockerfile
frontend/src/components/recordUserVideo/recordUserVideo-view.js
frontend/src/routes.js

Durante a gravação do vídeo são tiradas as fotos e salvas no ``` this.state.signatureImage ``` e é printado no console um log com o array, veja para validá-lo.
[ROTA](http://localhost:3001/record) para teste, logo após rodar `docker-compose build`
**Checklist**

Tirar foto durante gravacao

---

frontend/src/components/reviewUserVideo/index.js
frontend/src/components/reviewUserVideo/styles.js

Reestilizei a pagina de review<br>
**Checklist**

restyled the review page

---

docs/project/planoComunicacao.md
mkdocs.yml

Plano de Comunicação Interna criado, contendo informações sobre o planejamento da nossa comunicação e ferramentas utilizadas (#118 - @victoralvesgomide).
**Checklist**

Criar Plano de Comunicação Interna

---

.circleci/config.yml

Foi configurado a realização do deploy continuo da Documentação
**Checklist**

Automatic doc deploy

---

.circleci/config.yml

Foi feito a inserção do React no job que realiza a build no CircleCI; Para análise automatica da build do Frontend.<br>
**Checklist**

React in circle ci

---

docs/meetings/reuniao11_11_19.md
docs/project/useCasesDiagram.md
docs/sprints/sprint9.md
mkdocs.yml

Foi adicionado a documentação relacionado a sprint 9 e a reunião de sprint review, retrospective e planning.<br>
**Checklist**

Added sprint 9 documentation

---

.mailmap

reference about .mailmap file:
* https://git-scm.com/docs/git-shortlog#_mapping_authors

mapping commit author names

---

docs/project/vision-document.md

Refatoramento do documento de visão.
**Checklist**

adding refactored vision document

---

docs/project/fidelity_prototyping.md
mkdocs.yml

Foi feito o documento de protótipo de média fidelidade (@caue96  e @ViniciusPuerto ) para que se possa visualizar o protótipo do sistema feito no início do projeto. O acesso ao protótipo está presente dentro do link colocado no documento.<br>
**Checklist**

Adição do protótipo de fidelidade

---

docs/project/postmortem.md
mkdocs.yml

Foi feito o postmortem do projeto (#185 - @caue96) para que se possa visualizar todos os pontos negativos e positivos do projeto durante todo o tempo de desenvolvimento.<br>
**Checklist**

Postmortem do projeto
